# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRecordEdge():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_recordEdge(self):
    # Test name: recordEdge
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://trytestingthis.netlify.app/")
    # 2 | setWindowSize | 945x1012 | 
    self.driver.set_window_size(945, 1012)
    # 3 | click | id=fname | 
    self.driver.find_element(By.ID, "fname").click()
    # 4 | type | id=fname | Karim
    self.driver.find_element(By.ID, "fname").send_keys("Karim")
    # 5 | type | id=lname | Chowdhury
    self.driver.find_element(By.ID, "lname").send_keys("Chowdhury")
    # 6 | click | css=label:nth-child(14) | 
    self.driver.find_element(By.CSS_SELECTOR, "label:nth-child(14)").click()
    # 7 | click | id=option | 
    self.driver.find_element(By.ID, "option").click()
    # 8 | select | id=option | label=Option 1
    dropdown = self.driver.find_element(By.ID, "option")
    dropdown.find_element(By.XPATH, "//option[. = 'Option 1']").click()
    # 9 | click | name=option2 | 
    self.driver.find_element(By.NAME, "option2").click()
    # 10 | click | css=.btn | 
    self.vars["window_handles"] = self.driver.window_handles
    # 11 | selectWindow | handle=${win197} | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.vars["win197"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win197"])
  
